# CapsLockをCtrlにする
org.gnome.desktop.input-sources:
  xkb-options: "['ctrl:nocaps']"

# Dockの設定
org.gnome.shell.extensions.dash-to-dock:
  dock-fixed: false           # 自動的に隠す
  dock-position: BOTTOM       # Dockの位置を下側にする
  extend-height: false        # macOSのドック風にする
  unity-backlit-items: true   # アクティブなアイコンの背景を変える

# HiDPI対応
# https://wiki.archlinux.jp/index.php/GNOME/%E3%83%92%E3%83%B3%E3%83%88%E3%81%A8%E3%83%86%E3%82%AF%E3%83%8B%E3%83%83%E3%82%AF#Retina_.28HiDPI.29_.E3.83.87.E3.82.A3.E3.82.B9.E3.83.97.E3.83.AC.E3.82.A4.E3.81.AE.E3.82.B5.E3.83.9D.E3.83.BC.E3.83.88
org.gnome.desktop.interface:
  scaling-factor: 1

# タッチパッドのナチュラルスクロールをやめる
org.gnome.desktop.peripherals.touchpad:
  natural-scroll: false
