window:
  dimensions:
    columns: 80
    lines: 24
  decorations: none
font:
  normal:
    family: Cica
  size: 12
colors:
  primary:
    background: '0x000000'
    foreground: '0xeaeaea'
bell:
  duration: 0
shell:
  program: /bin/bash
  args:
    - --login
mouse:
  url:
    launcher: None
scrolling:
  history: 0
background_opacity: 0.8
live_config_reload: true
#debug:
#  render_timer: true
#  log_level: Trace
#  print_events: true
key_bindings:
  # Ctrl-CとSuper-Vをスワップする
  - { key: C,        mods: Control|Shift, action: Copy                   }
  - { key: Key0,     mods: Control,       action: ResetFontSize          }
  - { key: Semicolon,mods: Control,       action: IncreaseFontSize       }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize       }
  - { key: V,        mods: Control|Shift, action: Paste                  }
  - { key: V,        mods: Super,   chars: "\x16"                        }
  - { key: Insert,   mods: Shift,   action: Paste                        }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                   }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                   }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
  - { key: Left,                    chars: "\x1b[D",   mode: ~AppCursor  }
  - { key: Left,                    chars: "\x1bOD",   mode: AppCursor   }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                   }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }
  - { key: Right,                   chars: "\x1b[C",   mode: ~AppCursor  }
  - { key: Right,                   chars: "\x1bOC",   mode: AppCursor   }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                   }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                   }
  - { key: Up,                      chars: "\x1b[A",   mode: ~AppCursor  }
  - { key: Up,                      chars: "\x1bOA",   mode: AppCursor   }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                   }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                   }
  - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
  - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
